---
- name: Ensure apt works with https
  apt: name={{ item }} state=present
  with_items:
    - apt-transport-https
    - ca-certificates

 - name: Add docker GPG key
   apt_key:
     keyserver: "{{ docker_keyserver }}"
     id: "{{ docker_gpg_id }}"
     state: present

  - name: Add docker apt repository
    apt_repository:
      repo:"deb https://apt.dockerproject.org/repo {{ ansible_distribution|lower }}-{{ ansible_distribution_release }} main"
      state: present

  # TODO linux headers

  - name: Apt-get update
    apt:
      update_cache: yes

  - name: Install docker
    apt:
      name: docker-engine
      state: present
    notify: Start Docker
